language: node_js
node_js:
  - "7"

env:
  - DS_DB_HOST=localhost MYMONEY_DB_USER=travis MYMONEY_DB_PASS= MYMONEY_DB_NAME=mymoney MYMONEY_SERVER_NAME=localhost MYMONEY_SERVER_PROTOCOL=http

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE mymoney;'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cat src/sql/db.sql | mysql -h localhost -u travis mymoney
  - cat src/sql/data/*.sql | mysql -h localhost -u travis mymoney

script:
  - npm test

git:
  depth: 10
